//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASProj.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASProj.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _740ecb78aa4c10cb0a2170ea2350c337 {
            get {
                object obj = ResourceManager.GetObject("740ecb78aa4c10cb0a2170ea2350c337", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _8b40d0ff8c8592393ceffcbb0e9654d3 {
            get {
                object obj = ResourceManager.GetObject("8b40d0ff8c8592393ceffcbb0e9654d3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap a46c81229e41a8a4c365ce467fb23d5b {
            get {
                object obj = ResourceManager.GetObject("a46c81229e41a8a4c365ce467fb23d5b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap animesher_com_bird_fantasy_anime_nature_1145927 {
            get {
                object obj = ResourceManager.GetObject("animesher.com_bird-fantasy-anime-nature-1145927", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap arny_fjola {
            get {
                object obj = ResourceManager.GetObject("arny fjola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottom__1_ {
            get {
                object obj = ResourceManager.GetObject("bottom__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottom__2_ {
            get {
                object obj = ResourceManager.GetObject("bottom__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottom__3_ {
            get {
                object obj = ResourceManager.GetObject("bottom__3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottom__4_ {
            get {
                object obj = ResourceManager.GetObject("bottom__4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottom__5_ {
            get {
                object obj = ResourceManager.GetObject("bottom__5_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottom__6_ {
            get {
                object obj = ResourceManager.GetObject("bottom__6_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap bottom__7_ {
            get {
                object obj = ResourceManager.GetObject("bottom__7_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap brick {
            get {
                object obj = ResourceManager.GetObject("brick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap brickwall {
            get {
                object obj = ResourceManager.GetObject("brickwall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap controls_platformer {
            get {
                object obj = ResourceManager.GetObject("controls platformer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dark_blue_gradient_background_9562_1024x616 {
            get {
                object obj = ResourceManager.GetObject("dark-blue-gradient-background-9562-1024x616", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:0,&quot;Name&quot;:&quot;Test game 1&quot;,&quot;Icon&quot;:&quot;&quot;,&quot;Author&quot;:&quot;Daniel Adams&quot;,&quot;Genre&quot;:&quot;Action, FPS&quot;,&quot;Goal&quot;:&quot;Translate the following words!&quot;,&quot;Questions&quot;:[{&quot;Id&quot;:0,&quot;Description&quot;:&quot;What does the word isskapur mean?&quot;,&quot;Points&quot;:20,&quot;CorrectAnswer&quot;:&quot;fridge&quot;,&quot;Answers&quot;:[&quot;fridge&quot;,&quot;freezer&quot;,&quot;dog&quot;,&quot;cat&quot;,&quot;Iceland&quot;,&quot;indoors&quot;]},{&quot;Id&quot;:1,&quot;Description&quot;:&quot;What does the word hundur mean?&quot;,&quot;Points&quot;:20,&quot;CorrectAnswer&quot;:&quot;dog&quot;,&quot;Answers&quot;:[&quot;anteater&quot;,&quot;horse&quot;,&quot;dog&quot;,&quot;cat&quot;,&quot;elephant&quot;,&quot;orange&quot;]},{&quot;Id&quot;:2,&quot;Description&quot;:&quot;What does the word island mean?&quot;,&quot;Po [rest of string was truncated]&quot;;.
        /// </summary>
        public static string default_games {
            get {
                return ResourceManager.GetString("default_games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Blob&quot;:&quot;/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wgARCAEAAQADASIAAhEBAxEB/8QAGgABAAIDAQAAAAAAAAAAAAAAAAUGAQMEAv/EABkBAQADAQEAAAAAAAAAAAAAAAABAgMEBf/aAAwDAQACEAMQAAABog15QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD1LzWGWzqtjSV25SppiJrt5EWAAAAAAAAAAbddqtns68NuEEAOTrRNL1WqrZd2BXQAAAAAAAACSs8bJbcIWyAAAVizxtdawMe4AAAAAAAAey47To80EAA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string default_images {
            get {
                return ResourceManager.GetString("default_images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:&quot;21a5c192-f882-4c41-aada-d9d5908de6cc&quot;,&quot;Username&quot;:&quot;dandabs&quot;,&quot;Discriminator&quot;:9726,&quot;CreatedAt&quot;:&quot;2022-08-30T19:53:54.9443284+01:00&quot;,&quot;Password&quot;:&quot;722f15e47bb9b3db93ec653351344bb4aa0c478b09f8607e3a8096a9bc1f2e3f&quot;,&quot;Avatar&quot;:null,&quot;Banner&quot;:null,&quot;Character&quot;:{&quot;Hair&quot;:&quot;carola&quot;,&quot;Head&quot;:&quot;theresa&quot;,&quot;Body&quot;:&quot;theresa&quot;,&quot;Legs&quot;:&quot;gaga&quot;},&quot;Theme&quot;:null,&quot;Status&quot;:null,&quot;Transactions&quot;:[{&quot;Time&quot;:&quot;2022-09-01T10:42:16.6311442+01:00&quot;,&quot;Points&quot;:80,&quot;Description&quot;:&quot;Completed a game: Test game 1&quot;},{&quot;Time&quot;:&quot;2022-09-01T10:45:16.9293638+01:00&quot;,&quot;P [rest of string was truncated]&quot;;.
        /// </summary>
        public static string default_users {
            get {
                return ResourceManager.GetString("default_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ezgif_com_gif_maker {
            get {
                object obj = ResourceManager.GetObject("ezgif.com-gif-maker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap face__1_ {
            get {
                object obj = ResourceManager.GetObject("face__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap face__2_ {
            get {
                object obj = ResourceManager.GetObject("face__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap face__3_ {
            get {
                object obj = ResourceManager.GetObject("face__3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap face__4_ {
            get {
                object obj = ResourceManager.GetObject("face__4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap face__5_ {
            get {
                object obj = ResourceManager.GetObject("face__5_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap face__6_ {
            get {
                object obj = ResourceManager.GetObject("face__6_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap face__7_ {
            get {
                object obj = ResourceManager.GetObject("face__7_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FireBall {
            get {
                object obj = ResourceManager.GetObject("FireBall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FireBallAttack {
            get {
                object obj = ResourceManager.GetObject("FireBallAttack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Font_Awesome_6_Brands_Regular_400 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_6_Brands_Regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Font_Awesome_6_Free_Regular_400 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_6_Free_Regular_400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Font_Awesome_6_Free_Solid_900 {
            get {
                object obj = ResourceManager.GetObject("Font_Awesome_6_Free_Solid_900", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair__1_ {
            get {
                object obj = ResourceManager.GetObject("hair__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair__2_ {
            get {
                object obj = ResourceManager.GetObject("hair__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair__3_ {
            get {
                object obj = ResourceManager.GetObject("hair__3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair__4_ {
            get {
                object obj = ResourceManager.GetObject("hair__4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair__5_ {
            get {
                object obj = ResourceManager.GetObject("hair__5_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair__6_ {
            get {
                object obj = ResourceManager.GetObject("hair__6_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair__7_ {
            get {
                object obj = ResourceManager.GetObject("hair__7_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0000s_0000_hatari {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0000s_0000_hatari", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0000s_0001_theo {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0000s_0001_theo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0000s_0002_petra {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0000s_0002_petra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0000s_0003_gaga {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0000s_0003_gaga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0000s_0004_carola {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0000s_0004_carola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0000s_0005_sanna {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0000s_0005_sanna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0000s_0006_teresa {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0000s_0006_teresa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0001s_0000_hatari {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0001s_0000_hatari", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0001s_0001_theo {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0001s_0001_theo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0001s_0002_petra {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0001s_0002_petra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0001s_0003_gaga {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0001s_0003_gaga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0001s_0004_carola {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0001s_0004_carola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0001s_0005_sanna {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0001s_0005_sanna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0001s_0006_teresa {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0001s_0006_teresa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0002s_0000_hatari {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0002s_0000_hatari", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0002s_0001_theo {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0002s_0001_theo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0002s_0002_petra {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0002s_0002_petra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0002s_0003_gaga {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0002s_0003_gaga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0002s_0004_carola {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0002s_0004_carola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0002s_0005_sanna {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0002s_0005_sanna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0002s_0006_teresa {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0002s_0006_teresa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0003s_0000_hatari {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0003s_0000_hatari", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0003s_0001_theo {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0003s_0001_theo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0003s_0002_petra {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0003s_0002_petra", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0003s_0003_gaga {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0003s_0003_gaga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0003s_0004_carola {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0003s_0004_carola", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0003s_0005_sanna {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0003s_0005_sanna", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hair_0000s_0003s_0006_teresa {
            get {
                object obj = ResourceManager.GetObject("hair_0000s_0003s_0006_teresa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HD_wallpaper_anime_bird_anime_bird_cartoon_nature {
            get {
                object obj = ResourceManager.GetObject("HD-wallpaper-anime-bird-anime-bird-cartoon-nature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heart_empty {
            get {
                object obj = ResourceManager.GetObject("heart_empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap heart_full {
            get {
                object obj = ResourceManager.GetObject("heart_full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Hit_Super_Effective {
            get {
                object obj = ResourceManager.GetObject("Hit_Super_Effective", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageedit_1_6924211824 {
            get {
                object obj = ResourceManager.GetObject("imageedit_1_6924211824", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageedit_2_3131043951 {
            get {
                object obj = ResourceManager.GetObject("imageedit_2_3131043951", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageedit_2_31310439511 {
            get {
                object obj = ResourceManager.GetObject("imageedit_2_31310439511", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageedit_3_3894007498 {
            get {
                object obj = ResourceManager.GetObject("imageedit_3_3894007498", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageedit_4_9884017893 {
            get {
                object obj = ResourceManager.GetObject("imageedit_4_9884017893", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap imageedit_8_7025415654 {
            get {
                object obj = ResourceManager.GetObject("imageedit_8_7025415654", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap lizzo_bet_awards_5daad5_0_1x {
            get {
                object obj = ResourceManager.GetObject("lizzo-bet-awards-5daad5-0@1x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Manrope_VariableFont_wght {
            get {
                object obj = ResourceManager.GetObject("Manrope_VariableFont_wght", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap photo_1616108738832_504f7b6addf2 {
            get {
                object obj = ResourceManager.GetObject("photo-1616108738832-504f7b6addf2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pokemon_landscape_by_brainblower_d8i3udq_fullview {
            get {
                object obj = ResourceManager.GetObject("pokemon_landscape_by_brainblower_d8i3udq-fullview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PokemonDiamond {
            get {
                object obj = ResourceManager.GetObject("PokemonDiamond", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PokemonGb_RAeo {
            get {
                object obj = ResourceManager.GetObject("PokemonGb_RAeo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap t4ovzMA {
            get {
                object obj = ResourceManager.GetObject("t4ovzMA", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] The_Days_In_Swordcraft_Academy {
            get {
                object obj = ResourceManager.GetObject("The_Days_In_Swordcraft_Academy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] The_Days_In_Swordcraft_Academy2 {
            get {
                object obj = ResourceManager.GetObject("The_Days_In_Swordcraft_Academy2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap theresa_may_34 {
            get {
                object obj = ResourceManager.GetObject("theresa-may-34", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TheresaMay_070622_F3EN1K_jpg {
            get {
                object obj = ResourceManager.GetObject("TheresaMay_070622_F3EN1K.jpg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TheresaMay_070622_F3EN1K1 {
            get {
                object obj = ResourceManager.GetObject("TheresaMay_070622_F3EN1K1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap top__1_ {
            get {
                object obj = ResourceManager.GetObject("top__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap top__2_ {
            get {
                object obj = ResourceManager.GetObject("top__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap top__3_ {
            get {
                object obj = ResourceManager.GetObject("top__3_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap top__4_ {
            get {
                object obj = ResourceManager.GetObject("top__4_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap top__5_ {
            get {
                object obj = ResourceManager.GetObject("top__5_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap top__6_ {
            get {
                object obj = ResourceManager.GetObject("top__6_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap top__7_ {
            get {
                object obj = ResourceManager.GetObject("top__7_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tumblr_b95fc3c386f44f7b45e0ab738c952a0e_08b15f0f_1280 {
            get {
                object obj = ResourceManager.GetObject("tumblr_b95fc3c386f44f7b45e0ab738c952a0e_08b15f0f_1280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ww0_bizydale_nets {
            get {
                object obj = ResourceManager.GetObject("ww0_bizydale_nets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ww0_bizydale_nets1 {
            get {
                object obj = ResourceManager.GetObject("ww0_bizydale_nets1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
